Adjust and export interfaces
selsa-inube/inubekit-table pull request #4
Opened 2024-03-21 21:26 UTC by JanuarAsprilla

The names of the interfaces used by the `<Table />` component were refactored, as well as how they are exported.

2024-03-27 16:24 UTC, wfercanas requested changes

2024-03-27 16:24 UTC, wfercanas commented on src/Table/index.tsx
> +interface ITableIActions {
Rename to `ITableActions`

2024-03-27 16:24 UTC, wfercanas commented on src/Table/index.tsx
> +interface ITableITitle {
Rename to `ITableTitle`

2024-03-27 16:24 UTC, wfercanas commented on src/Table/index.tsx
> +interface ITableIAction {
`ITableAction`

2024-03-27 16:24 UTC, wfercanas commented on src/Table/index.tsx
> +interface ITableITableUI {
`ITableUI`

2024-03-30 05:17 UTC, JanuarAsprilla commented on src/Table/index.tsx
> +interface ITableIActions {
solved

2024-03-30 05:19 UTC, JanuarAsprilla commented on src/Table/index.tsx
> +interface ITableITableUI {
solved

2024-03-30 05:19 UTC, JanuarAsprilla commented on src/Table/index.tsx
> +interface ITableIAction {
solved

2024-03-30 05:20 UTC, JanuarAsprilla commented on src/Table/index.tsx
> +interface ITableITitle {
solved

2024-04-01 20:21 UTC, wfercanas requested changes

2024-04-01 20:21 UTC, wfercanas commented on src/Table/props.ts
> +import { ITableActions } from ".";
Although sometimes we define interfaces in index.tsx and other times in props.ts, at the end an interface has to be in only one of those files, not in both.

These interfaces are in both files, which is incorrect.

**Fix: define the interfaces in props.ts**

2024-04-01 20:21 UTC, wfercanas commented on src/index.ts
Export here the interfaces from props.ts

2024-04-01 21:02 UTC, JanuarAsprilla commented on src/Table/props.ts
> +import { ITableActions } from ".";
solved

2024-04-01 21:02 UTC, JanuarAsprilla commented on src/index.ts
solved

2024-04-02 14:44 UTC, wfercanas requested changes

2024-04-02 14:44 UTC, wfercanas commented on src/Table/index.tsx
> +};
Sorry, here we don't have to export the interfaces, that job is already done by props.ts

2024-04-02 14:44 UTC, wfercanas commented on src/index.ts
> +} from "./Table";
Use props.ts here instead

2024-04-02 16:16 UTC, JanuarAsprilla commented on src/Table/index.tsx
> +};
solved

2024-04-02 21:23 UTC, merged